# -*- coding: utf-8 -*-
"""Detecção de imagens com pessoas.ipynb

Automatically generated by Colaboratory.

"""

from google.colab import drive
drive.mount('/content/drive')

!ls drive/My\ Drive/People_Detection/dadosImagem

!ln -s drive/My\ Drive/People_Detection/dadosImagem /content/Aula

!ls Aula/Treinamento/positivos

import cv2

img_caminho = 'Aula/Treinamento/positivos/crop_000010.png'
img_teste = cv2.imread(img_caminho)

cv2.imshow('img',img_teste)

from google.colab.patches import cv2_imshow

cv2_imshow(img_teste)

print(type(img_teste)) #RGB - Red Green Blue
print(img_teste.shape)

import numpy as np

print(img_teste)

print("Minimo: ", np.min(img_teste))
print("Máximo: ", np.max(img_teste))